## Welcome to Jupyter

In [4]:
from random import randint
a = 3
b = 7.8
c = 'dont forget to run cells'
# we may see immediate assets
# a # this uses __repr__
# b

In [5]:
c

'dont forget to run cells'

In [6]:
r = randint(0,10)
print(f'Random integer is {r}')

Random integer is 7


### Numpy Overview
Numpy is numeric python - very useful for data anaylsis

In [8]:
# numpy needs to be imported
import numpy as np

In [9]:
# Numpy offers additional data structures
# the arange is an array-range object
n = np.arange(2,8,0.5) # start, stop-before, step
n # all members must be the same data type
n.dtype # numpy will choose the relevant dtype: int or float

dtype('float64')

In [10]:
# we will build an array of random values
m = np.random.randn(9,3) # we will have an array shaped 9 by 3
m.dtype
m.shape
m

array([[-0.3879973 ,  0.17880757,  0.04970688],
       [ 0.47155012, -0.76703842, -1.62546036],
       [ 0.18901631, -1.16532939, -2.22552452],
       [-1.59969637,  0.24205535, -0.73916457],
       [-0.63008515,  0.16443618, -3.22822155],
       [ 0.03525033,  0.5765039 , -0.01227976],
       [-1.57626216, -0.55759998, -0.43007183],
       [ 1.05978175, -0.0533872 ,  0.72743168],
       [-0.7633529 , -0.63857356,  1.27418565]])

In [11]:
# multi-dimensional arrays
e = np.random.randn(2,3,4,5,2,3)
e # we have a six dimensional array

array([[[[[[ 5.70568758e-01,  1.16642345e+00,  3.24885503e-01],
           [ 6.96976055e-01,  1.53594199e+00, -3.43165412e+00]],

          [[ 4.93095583e-01,  5.81788728e-01,  1.13328202e+00],
           [ 6.15380554e-02, -1.52136076e+00, -1.80989964e+00]],

          [[-1.00664022e+00, -8.67581462e-02, -1.04658099e+00],
           [ 1.60971851e+00,  1.04984108e+00, -6.78685142e-01]],

          [[ 1.10843810e+00,  7.17279512e-02, -1.01725745e+00],
           [-6.52426491e-01,  5.71909947e-01, -4.91166634e-01]],

          [[-6.67719269e-02,  8.64600852e-01,  5.30691404e-02],
           [-7.05996613e-01,  7.03705922e-01, -1.61173416e+00]]],


         [[[ 7.95010567e-01,  7.38396264e-01,  5.62134692e-01],
           [-5.74920446e-01,  1.70645196e-02,  1.82824792e+00]],

          [[ 3.65372452e-01, -5.34992730e-01, -5.61965583e-01],
           [ 8.46690222e-01, -2.78616305e-01, -7.69982487e-02]],

          [[-2.42021283e-01,  4.29221343e-01,  2.37644980e-01],
           [ 3.98957685e

In [12]:
# creating arrays
# careful 'empty' may choose memory that has left-over data in it!!!!!!!
f = np.empty( (3,6) ) # find some memory and create an array there
f= np.zeros( (3,6), 'int32' )
f.dtype
f

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

### Working with Arrays

In [14]:
s = f.astype(np.str_)
s
i = s.astype(np.float32)
i

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)

In [24]:
# We may carry out calculations across arrays
z = np.zeros((3,3,3,3)) # this is a tuple of dimensions
z = np.random.randn(9000,9000)
powers = (z+3)**2
powers

array([[12.44037361, 10.01084237,  0.12764676, ..., 11.08950829,
         1.59137215,  9.5982622 ],
       [10.61123885, 20.60533156,  6.548967  , ...,  3.52216608,
        13.35110811,  9.04604045],
       [ 3.09943461,  8.66131082, 13.97315033, ..., 11.94735767,
        26.36282605, 19.45050671],
       ...,
       [ 8.70492208,  0.58996974,  2.82545823, ..., 24.923295  ,
        18.05164811, 11.41713832],
       [17.71118793,  7.34498691, 18.96528599, ..., 15.15076971,
        14.9397535 , 10.67114255],
       [28.45147898,  4.95942285, 13.86524455, ..., 13.40427382,
         9.3413253 , 17.79086858]])

In [28]:
# we may apply any mathematics across all membrs of the array e.g. (z-2)*0.5/f
# we may apply slicing to arrays just like in Python
z[0:5:2]
z[::-1] # reverse the array

array([[ 2.33399278, -0.77302383,  0.72360639, ...,  0.66118476,
         0.05635818,  1.21792231],
       [ 1.20846622, -0.28983637,  1.35491515, ...,  0.89239897,
         0.86519773,  0.26667148],
       [-0.04958951, -2.23190513, -1.31909006, ...,  1.99232361,
         1.24872312,  0.37892562],
       ...,
       [-1.23947888, -0.0569895 ,  0.73806773, ...,  0.456495  ,
         2.13447427,  1.41027286],
       [ 0.25748965,  1.53930959, -0.44090504, ..., -1.12325652,
         0.65391682,  0.00766362],
       [ 0.52709138,  0.16399153, -2.64272314, ...,  0.33009133,
        -1.738504  ,  0.09810623]])

In [52]:
# We may access any member of an array
z[0,1]=99 # mutate the value at this location
z[0,1]

99.0

In [60]:
i.shape

(3, 6)

In [64]:
i.T # transpose the entire array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)